spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.example.ordermanagementapi: INFO

server:
  port: 8080
  compression:
    enabled: true

springdoc:
  swagger-ui:
    enabled: false
